"""add is_active bool to consumerpowereq

Revision ID: 91fcb1497c4f
Revises: db4c88cd40d3
Create Date: 2026-04-15 12:58:10.157529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91fcb1497c4f'
down_revision: Union[str, Sequence[str], None] = 'db4c88cd40d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('required_power', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('required_power', 'is_active')
    # ### end Alembic commands ###
